"""add orders e order_items

Revision ID: 8763f4c626be
Revises: 
Create Date: 2026-05-24 05:34:09.654167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8763f4c626be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('endereco_rua', sa.String(length=200), nullable=False),
    sa.Column('endereco_numero', sa.String(length=20), nullable=False),
    sa.Column('endereco_bairro', sa.String(length=100), nullable=False),
    sa.Column('endereco_cidade', sa.String(length=100), nullable=False),
    sa.Column('endereco_estado', sa.String(length=2), nullable=False),
    sa.Column('endereco_cep', sa.String(length=9), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_items')
    op.drop_table('orders')
    # ### end Alembic commands ###
